### ISSUE TITLE
[Feature request] Add option to subsample reads

### ISSUE THREAD

**Issue by y9c** [smithlabcode/falco#35] opened 2022-08-07 01:37 UTC
In most of the time, we run falco (fastqc) to have a rough estimation on data quality. So we do not need to parse every single read in the fastq file. I think we can randomly subsample certain amount/ fraction of reads to increase the speed or save computational power. 

It is possible to add a argument (`--subsample/-s`) for this?

Thanks!

**Comment by toddrichmond** [comment] 2022-08-11 14:51
This would be incredibly useful to me as well.

**Comment by guilhermesena1** [comment] 2022-08-11 23:17
that's definitely a useful feature, an easy thing to implement, and I can take care of it in the coming days!

**Comment by guilhermesena1** [comment] 2022-08-23 01:42
Thanks for the suggestion to add this functionality! I gave it a shot at 009c28e . You definitely seem to be onto something, in that only processing every 20th read, for example, seems to give very similar results in most FASTQ files but is more than twice as fast processing the full dataset :) might need more testing to make sure nothing broke and would welcome any feedback.

**Comment by guilhermesena1** [comment] 2022-09-06 12:10
I'm going to close this one (this feature was added at 1.1.0), but if there are further problems with the flag or it doesn't work as intended, please feel free to reopen or create a new issue!

**Closed by guilhermesena1** 2022-09-06 12:10 UTC
Labels: enhancement
