### ISSUE TITLE
Broken script in HTML report

### ISSUE THREAD

**Issue by RoadRoller** [smithlabcode/falco#22] opened 2022-01-12 11:13 UTC
Falco version 0.3.0.

Generated HTML report:
[fastqc_report.html.zip](https://github.com/smithlabcode/falco/files/7854053/fastqc_report.html.zip)
contains number with leading zeros (`y : [004.29734000000]`) in section for K-mer chart. It's not valid JavaScript syntax, so script is broken and all charts dissapper from report.

**Comment by andrewdavidsmith** [comment] 2022-09-03 00:10
@RoadRoller I can't test this directly for your case, as I would need to very precisely simulate the number of k-mers to report, but I found what seems like the cause of this problem. There was a bug in how we insert commas into that `004.29734000000`. It should have had 10 numbers I think, just as with entries immediately prior in your file. The fix is in commit 78eac8d44b67c04005542855d70aafe1879a608c. I'm closing this issue and will reopen if needed.

**Closed by andrewdavidsmith** 2022-09-03 00:10 UTC
Labels: bug
